MPocket/Controllers/RegisterUserController.cs
using MPocket.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EntityDatabase.Models;

namespace MPocket.Controllers
{
    public class RegisterUserController : Controller
    {
        // GET: RegisterUser
        public ActionResult RegisterUserView()
        {
            return View();
        }

        [HttpPost]
        public ActionResult RegisterUser(UserModel model)
        {
            User user = model.Get(model);
            if(user == null)
            {
                model.Register(model);
            }
            ModelState.Clear();
            return View("RegisterUserView");
        }
    }
}

MPocket/Controllers/UserLoginController.cs
using EntityDatabase.Models;
using MPocket.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MPocketCommon.Helpers;
using MPocketCommon.Cryptography;
using MPocket.Utils;

namespace MPocket.Controllers
{
    public class UserLoginController : Controller
    {
        // GET: UserLogin
        public ActionResult UserLoginView()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(UserModel model)
        {
            User user = model.Get(model);           
            if (user != null)
            {
                SessionManager sessionManager = new SessionManager();
                bool passwordCorrect = CheckPassword(user.Password, model.Password);

                if (passwordCorrect)
                {
                    if (!user.IsActive)
                    {
                        user.IsActive = true;
                        model.UpdateUser(user);                       
                    }

                    sessionManager.Add<User>(user, PageConstant.USER_ID_I_SESSION);
                    ViewBag.Name = user.Name;

                    BudgetModel bmodel = new BudgetModel();
                    Budget budget = bmodel.GetCurrentBudget(user.Id);

                    if (budget == null)
                    {
                        return RedirectToAction("FirstLaunch", "FirstLaunch");
                    }
                  
                    sessionManager.Add<Budget>(budget, PageConstant.BUDGET_ID_IN_SESSION);

                    bmodel.CurrentBudget = budget.CurrentBudget;
                    bmodel.StartBudget = budget.StartBudget;
                    return View("MainPanel", bmodel);
                }                             
            }
            else
            {
                ModelState.AddModelError("", "Error");
            }

            ModelState.Clear();
            return View("UserLoginView");
        }

        private bool CheckPassword(string password, string passwordToCheck)
        {
            ICryptography pass = new PasswordManager();
            return pass.IsMatch(password, pass.Encrypt(passwordToCheck)); 
        }

    }
}

MPocket/Views/UserLogin/UserLoginView.cshtml
@model MPocket.Models.UserModel

@using (Html.BeginForm("Login", "UserLogin"))
{
    <div>
        <div class="row">
            <div class="col-md-offset-5 col-md-3" style="width:300px; height:400px; background:#f5f5f0">
                <div class="form-login">
                    <h4>Zaloguj się</h4>
                    @Html.TextBoxFor(m => m.Login, new {@class="form-control input-sm chat-input", @placeholder="adres email"})
                    <br />
                    @Html.TextBoxFor(m => m.Password, new { @class = "form-control input-sm chat-input", @placeholder = "hasło", @type="password" })
                    <br />
                    <div class="wrapper">
                        <span class="group-btn">
                            <button type="submit" class="btn btn-default" style="width:auto" onclick="location.href='@Url.Action("MainPanel", "MainPanel")'">Zaloguj</button>
                        </span>
                    </div>
                </div>
                <br />
                <div class="form-login">
                    <div class="wrapper">
                        <span>Nie masz konta? @Html.ActionLink("Zarejestruj się.", "RegisterUserView", "RegisterUser")</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
}