MPocket/Controllers/FirstLaunchController.cs
using EntityDatabase.Models;
using MPocket.Models;
using MPocket.Utils;
using MPocketCommon.Helpers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MPocket.Controllers
{
    public class FirstLaunchController : Controller
    {
        // GET: FirstLaunch
        public ActionResult FirstLaunch(FirstLaunchModel model)
        {
            return View(model);
        }

        public ActionResult Save(FirstLaunchModel model)
        {
            BudgetModel budgetModel = new BudgetModel();
            SettingsModel settingModel = new SettingsModel();
            SessionManager sessionManager = new SessionManager();
            int userid = sessionManager.Get<User>(PageConstant.USER_ID_I_SESSION).Id;
            
            budgetModel = model.Budget;
            settingModel = model.Settings;                   
            budgetModel.UserId = settingModel.UserId = userid;
            budgetModel.AddBudget(budgetModel);
            settingModel.AddSettings(settingModel);

            Budget budget = budgetModel.GetCurrentBudget(userid);
            sessionManager.Add<Budget>(budget, PageConstant.BUDGET_ID_IN_SESSION);
            budgetModel.CurrentBudget = budget.CurrentBudget;
            budgetModel.StartBudget = budget.StartBudget;

            return View("MainPanel", budgetModel);
        }
    }
}

MPocket/Views/FirstLaunch/FirstLaunch.cshtml
@model MPocket.Models.FirstLaunchModel
<br />

@using (Html.BeginForm("Save", "FirstLaunch"))
{
    <div class="form-group">
        <label>Budżet</label>
        @Html.TextBoxFor(m =>m.Budget.StartBudget, new { @class = "form-control", @style = "width:138px" })
    </div>
    <div class="form-group form-inline">
        <div class="form-group">
            <label>Początek okresu</label>
            @Html.TextBoxFor(m => m.Budget.StartDate, new { @class = "form-control" })
        </div>
        <div class="form-group">
            <label>Koniec okresu</label>
            @Html.TextBoxFor(m => m.Budget.EndDate, new { @class = "form-control"})
        </div>      
    </div>
    <br />
    <div class="checkbox">
        <label>@Html.CheckBoxFor(m =>m.Settings.IsManual) />Automatycznie przedłużaj budżet</label>
    </div>
    <button type="submit" class="btn btn-default">Zapisz</button>
}