MPocket/Controllers/BudgetController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MPocket.Models;
using EntityDatabase.Models;
using MPocketCommon.Helpers;
using MPocket.Utils;

namespace MPocket.Controllers
{
    public class BudgetController : Controller
    {
        // GET: Budget
        public ActionResult Index()
        {
            BudgetModel model = new BudgetModel();
            SessionManager session = new SessionManager();
            Budget budget = model.GetBudgetById(session.Get<Budget>(PageConstant.BUDGET_ID_IN_SESSION).Id);
            model.CurrentBudget = budget.CurrentBudget;
            model.EndDate = budget.EndDate;
            model.StartDate = budget.StartDate;
            model.StartBudget = budget.StartBudget;
            return View(model);
        }

        public ActionResult Update(BudgetModel model)
        {
            SessionManager session = new SessionManager();
            Budget budget = model.GetBudgetById(session.Get<Budget>(PageConstant.BUDGET_ID_IN_SESSION).Id);
            model.StartBudget = budget.StartBudget + model.AddedBudget;
            model.CurrentBudget = budget.CurrentBudget + model.AddedBudget;
            budget.StartBudget = model.StartBudget;
            budget.CurrentBudget = model.CurrentBudget;
            model.UpdateBudget(budget);
            return View("MainPanel", model);
        }
    }
}

MPocket/Controllers/HistoryController.cs
using EntityDatabase.Models;
using MPocket.Models;
using MPocket.Utils;
using MPocket.ViewsModel;
using MPocketCommon.Helpers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MPocket.Controllers
{
    public class HistoryController : Controller
    {
        // GET: History
        public ActionResult Index()
        {
            BudgetModel model = new BudgetModel();
            SessionManager session = new SessionManager();

            BudgetViewModel views = new BudgetViewModel()
            {
                Budget = model.GetAll(session.Get<User>(PageConstant.USER_ID_I_SESSION).Id)
            };

            return View(views);
        }

        public ActionResult Load(string[] selected)
        {
            SessionManager session = new SessionManager();
            BudgetModel bmodel = new BudgetModel();
            Budget budget = bmodel.GetBudgetById(int.Parse(selected.First()));

            session.Replace<Budget>(budget, PageConstant.BUDGET_ID_IN_SESSION);
            bmodel.StartBudget = budget.StartBudget;
            bmodel.CurrentBudget = budget.CurrentBudget;
            return View("MainPanel", bmodel);
        }
    }
}

MPocket/Controllers/LogOutController.cs
using MPocket.Utils;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MPocket.Controllers
{
    public class LogOutController : Controller
    {
        // GET: LogOut
        public ActionResult Index()
        {
            SessionManager session = new SessionManager();
            session.RemoveSession();
            return RedirectToAction("UserLoginView", "UserLogin");
        }
    }
}

MPocket/Controllers/MainPanelController.cs
using MPocket.Models;
using MPocketCommon.Helpers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MPocket.Controllers
{
    public class MainPanelController : BaseController
    {
        // GET: MainPanel
        public ActionResult MainPanel()
        {
            return View();
        }
    }
}

MPocket/Controllers/SummaryController.cs
using EntityDatabase.Models;
using MPocket.Models;
using MPocket.Utils;
using MPocket.ViewsModel;
using MPocketCommon.Helpers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MPocket.Controllers
{
    public class SummaryController : Controller
    {
        // GET: Summary
        public ActionResult Index()
        {
            ExpensesModel model = new ExpensesModel();
            BudgetModel bModel = new BudgetModel();
            SessionManager session = new SessionManager();
            int budgetId = session.Get<Budget>(PageConstant.BUDGET_ID_IN_SESSION).Id;
            int userId = session.Get<User>(PageConstant.USER_ID_I_SESSION).Id;
            var expense = model.GetAll(budgetId);

            var viewModel = new SummaryModel()
            {
                Summary = expense
            };


            return View(viewModel);
        }
    }
}

MPocket/Views/Shared/BudgetSummary.cshtml
@model MPocket.Models.BudgetModel


    @*<label>@string.Format("Twój budżet wynosi: {0:#.00} zł", 100.12)</label>*@
<label>@string.Format("Twój budżet wynosi: {0:#.00}zł / {1:#.00}zł", Model == null ? 0 :Model.StartBudget, Model == null ? 0 : Model.CurrentBudget)</label>

MPocket/Views/Shared/CentralView.cshtml
@model MPocket.Models.ExpensesModel

<br />
@using (Html.BeginForm("Save", "CentralPanel"))
{
    <div class="form-group">
        <div class="form-group">
            <label>Kwota</label>
            @Html.TextBoxFor(m => m.Amount, new { @placeholder = "kwota", @class = "form-control", @autocomplete = "off", @style = "width:138px" })
        </div>
        <div class="form-group">
            <label>Opis</label>
            @Html.TextBoxFor(m => m.Description, new { @placeholder = "opis", @class = "form-control", @style = "width:400px" })           
        </div>                
     </div>
    <button type="submit" class="btn btn-default">Zapisz</button>
}

MPocket/Views/Shared/MainPanel.cshtml
@model MPocket.Models.BudgetModel

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MPocket</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    <script src="@Url.Content("~/Scripts/jquery.unobtrusive-ajax.js")" type="text/javascript"></script>
</head>
<body>
    @*@RenderBody()*@
    @Html.Partial("_NavBar", Model)
    <div class="container">
        <div class="row">
            <div class="col-md-4 col-md-offset-0">
                <div>
                    <br />
                    <ul class="list-group">
                        <li class="list-group-item">
                            <a id="expense" class="btn" style="font-size:larger; color:dimgray">Wprowadź wydatki</a>
                        </li>
                        <li class="list-group-item">
                            <a id="summary" class="btn" style="font-size:larger; color:dimgray">Analiza wydatków</a>
                        </li>
                        <li class="list-group-item">
                            <a id="budget" class="btn" style="font-size:larger; color:dimgray">Budżet</a>
                        </li>
                        <li class="list-group-item">
                            <a id="settings" class="btn" style="font-size:larger; color:dimgray">Ustawienia</a>
                        </li>  
                        <li class="list-group-item">
                            <a id="history" class="btn" style="font-size:larger; color:dimgray">Historia</a>
                        </li> 
                    </ul>
                </div>                
            </div>
            <div class="col-md-8" id="output">
                
            </div>
        </div>

    <footer class="navbar-fixed-bottom panel-footer">
        <p>&copy; @DateTime.Now.Year - MPocket application by Tomasz Kaczmarek</p>
    </footer>
    </div>

    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $("#expense").click(function () {
                $.ajax({
                    url: '@Url.Action("CentralView", "CentralPanel")',
                    dataType: "html",
                    type: "GET",
                    contentType: "application/html; charset=utf-8",
                    success: function (result) {
                        //alert("success");
                        $("#output").html(result);
                    },
                    error: function (xhr) {
                        alert("error");
                    }
                });
            });
        })
    </script>

    <script type="text/javascript">
        $(document).ready(function () {
            $("#summary").click(function () {
                $.ajax({
                    url: '@Url.Action("Index", "Summary")',
                    dataType: "html",
                    type: "GET",
                    contentType: "application/html; charset=utf-8",
                    success: function (result) {
                        //alert("success");
                        $("#output").html(result);
                    },
                    error: function (xhr) {
                        alert("error");
                    }
                });
            });
        })
    </script>

    <script type="text/javascript">
        $(document).ready(function () {
            $("#settings").click(function () {
                $.ajax({
                    url: '@Url.Action("Index", "Settings")',
                    dataType: "html",
                    type: "GET",
                    contentType: "application/html; charset=utf-8",
                    success: function (result) {
                        //alert("success");
                        $("#output").html(result);
                    },
                    error: function (xhr) {
                        alert("error");
                    }
                });
            });
        })
    </script>

    <script type="text/javascript">
        $(document).ready(function () {
            $("#budget").click(function () {
                $.ajax({
                    url: '@Url.Action("Index", "Budget")',
                    dataType: "html",
                    type: "GET",
                    contentType: "application/html; charset=utf-8",
                    success: function (result) {
                        //alert("success");
                        $("#output").html(result);
                    },
                    error: function (xhr) {
                        alert("error");
                    }
                });
            });
        })
    </script>

    <script type="text/javascript">
        $(document).ready(function () {
            $("#history").click(function () {
                $.ajax({
                    url: '@Url.Action("Index", "History")',
                    dataType: "html",
                    type: "GET",
                    contentType: "application/html; charset=utf-8",
                    success: function (result) {
                        //alert("success");
                        $("#output").html(result);
                    },
                    error: function (xhr) {
                        alert("error");
                    }
                });
            });
        })
    </script>
</body>
</html>

MPocket/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MPocket</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @RenderBody()

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

MPocket/Views/Shared/_NavBar.cshtml
@using MPocketCommon.Helpers
@using MPocket.Utils
@using EntityDatabase.Models
@model MPocket.Models.BudgetModel

<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="collapse navbar-collapse">
            <p class="navbar-text navbar-left">
                LOGO
            </p>
    
            <p class="navbar-text navbar-right">
                @Html.Partial("BudgetSummary", Model)
                
                @{
                    SessionManager session = new SessionManager();
                    string name = session.Get<User>(PageConstant.USER_ID_I_SESSION).Name;
                }
                <a>@name</a>
                @*<a>Avatar</a>*@
                @Html.ActionLink("Wyloguj", "Index", "LogOut")
            </a>
        </div>
    </div>
</div>